### ISSUE TITLE
Apple will stop accepting submissions of apps that use UIWebView APIs

### ISSUE THREAD

**Issue by ronnie70** [sgr-ksmt/PDFGenerator#115]
After uploading our app to AppStoreConnect, I received the following email from Apple:

> Dear Developer,
> We identified one or more issues with a recent delivery for your app, "autoSense Fuel DEV" 1.2.1 (2). Your delivery was successful, but you may wish to correct the following issues in your next delivery:
> ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of apps that use UIWebView APIs . See https://developer.apple.com/documentation/uikit/uiwebview for more information.
> After you’ve corrected the issues, you can use Xcode or Application Loader to upload a new binary to App Store Connect.
> Best regards,
> The App Store Team

Is somebody already working on replacing UIWebView (APIs) with WKWebView? If not, I will probably fork it myself.

**Comment by fo24** [comment]
Any updates ?

**Comment by rlester** [comment]
https://github.com/sgr-ksmt/PDFGenerator/pull/117

**Comment by sgr-ksmt** [comment]
I'm really sorry for the late reply to you.
I have just publihsed v3.1.0 to resolve this issue.
Thanks @rlester 🙏

**Comment by ronnie70** [comment]
Awesome! 👍

**Comment by rlester** [comment]
I think we're good to close this no?

**Comment by ronnie70** [comment]
Yes! Sorry...
