### ISSUE TITLE
issue with tableView

### ISSUE THREAD

**Issue by grandM** [sgr-ksmt/PDFGenerator#13]
First of all I want to congratulate you on your effort. It still has a small bug though. The first section header of a section is being shown but not at the top. In attachment you can see the error. I used the default UITableViewController. 
[sample1 kopie.pdf](https://github.com/sgr-ksmt/PDFGenerator/files/148757/sample1.kopie.pdf)

**Comment by sgr-ksmt** [comment]
Thanks for reporting issue! e I'll work to resolve this issue. Please wait for a little while. :cry:

**Comment by sgr-ksmt** [comment]
@grandM 
Finally, I found a bug :smile: 
 If tableview has `sectionInset`, first section header got out of top position.
(or If set `Adjust Scroll View Inset` in storyboard.
I'll work to resolve this issue. Please wait for a little while!!
