### ISSUE TITLE
Using Storyboards

### ISSUE THREAD

**Issue by johnslay** [sgr-ksmt/PDFGenerator#20]
Hey is it possible to take the view from a storyboard without displaying it on the screen and convert it to a PDF? I'm trying but I keep getting the ZeroSizeView error.

Code:
```
 let storyboard = UIStoryboard(name: "Overview", bundle: NSBundle.mainBundle())
        
 let vc = storyboard.instantiateViewControllerWithIdentifier("Overview")
        
 let view = vc.view
```

Error:

`ZeroSizeView(<UITableView: 0x7dbfd600; frame = (0 0; 1024 768); clipsToBounds = YES; autoresize = W+H; gestureRecognizers = <NSArray: 0x7c8d6960>; layer = <CALayer: 0x7c8d2880>; contentOffset: {0, 0}; contentSize: {1024, 0}>)`

Thanks, I appreciate the service.

**Comment by sgr-ksmt** [comment]
HI, @johnslay 

If a view is __UITableView__ , check not _frame's size_ but _contentSize_ .

> ZeroSizeView(\<UITableView: 0x7dbfd600; frame = (0 0; 1024 768); clipsToBounds = YES; autoresize = W+H; gestureRecognizers = \<NSArray: 0x7c8d6960\>; layer = \<CALayer: 0x7c8d2880\>; contentOffset: {0, 0}; contentSize: {1024, 0}\>)

Frame's size is {1024 768}, but _contentSize_ is equal to __CGSizeZero__ .

Please check table view's contentSize and retry! :smile:

**Comment by johnslay** [comment]
@jagsrajput21 I can't remember if I ever solved it and I don't have the code anymore, sorry :(

**Comment by mkayswork** [comment]
@jagsrajput21 make sure to set the contentSize with a height != 0. 
I defined a scrollView with this sample got and got no error: 

`let scrollView = UIScrollView(frame: CGRect(x: 0, y: 0, width: 595, height: 0))
        scrollView.contentSize = CGSize(width: 595, height: 100)`

**Comment by timgerdes93** [comment]
I had the problem that all my constraints were gone after rendering. Everything was out of position and my button to render the pdf also was on a size of 0. 

After I did add this line of code to the view that the pdf is rendering everything worked like charm.
`.translatesAutoresizingMaskIntoConstraints = true`
