### ISSUE TITLE
PDFGenerator 1.1.4 has not released on CocoaPods

### ISSUE THREAD

**Issue by jagajagachan** [sgr-ksmt/PDFGenerator#23]
Hi

I love PDFGenerator.
I want to update version 1.1.4 on CocoaPods.
But the version has been still 1.1.3.
https://cocoapods.org/pods/PDFGenerator

Could you confirm the CocoaPods?

Thx.

**Comment by sgr-ksmt** [comment]
@jagajagachan 

Sorry... I forgot to push library to CocoaPods.
I just push now!

Thx for reporting :)
