### ISSUE TITLE
How use this framework in Objective-C Project?

### ISSUE THREAD

**Issue by qasimmehboob** [sgr-ksmt/PDFGenerator#24]
I want to use this framework in my Objective-C Project. Please can you give me sample code to use this in objective-c ? i need it urgent.

**Comment by sgr-ksmt** [comment]
@qasimmehboob 
Sorry, this library currently support only Swift. All of functions can't be called from Objective-C.
If want to use from Objective-C, I have to renovate this library overall.

**Comment by qasimmehboob** [comment]
@sgr-ksmt 
Thank you for reply. 
I was able to generate single page pdf using code from this link ([ http://ipdfdev.com/2011/04/22/convert-an-image-to-pdf-on-the-iphone-and-ipad/]. The problem in this code was it is not generate multi page pdf so i want to use your framework for multi page pdf. 
But with little effort and little modification in code i generated multi page pdf with same code from above link. So now code is working for me. But anyway thanx for your urgent reply. your framework is good in future may be i use this in my new swift app. :)
