### ISSUE TITLE
support swift 2.3

### ISSUE THREAD

**Issue by sgr-ksmt** [sgr-ksmt/PDFGenerator#26]
- [ ] Edit travis for Xcode 8 beta, swift2.3

**Comment by TheDarkCode** [comment]
I added Swift 3 support in #28. Swift 2.3 is really not worth the effort unless your codebase is so large, heavily reliant on dependencies that are only Swift 2.x, and - cost-wise - not worth the effort to migrate. By default, you should be choosing Swift 3 over 2.3.
