### ISSUE TITLE
Create multipage from uitableview

### ISSUE THREAD

**Issue by HoangDuoc** [sgr-ksmt/PDFGenerator#35]
I have a tableview with multi cell. when i generate pdf file, it's a long page. How do i generate pdf file with multi page ??? Help me !!

**Comment by sgr-ksmt** [comment]
@HoangDuoc 


I'm sorry for the late reply..
Generating multi page from uitableview's cells is not supported. sorry 😢 
I will consider this problem..

**Comment by tryWabbit** [comment]
Any update?
