### ISSUE TITLE
Swift 2.3 pod install instructions not working?

### ISSUE THREAD

**Issue by proxyblue** [sgr-ksmt/PDFGenerator#64]
Hey guys,

I wasn't able to follow the instructions correctly for installing the Swift 2.3 branch.

I added this to my pod file
```
    # Swift 2.3
    pod 'PDFGenerator', :branch => 'swift-2.3'
```

and I keep getting this:
`[!] Unknown external source parameters for `PDFGenerator`: `{:branch=>"swift-2.3"}`
`

However, I managed to get this to work. Not sure why or what's changed - but hopefully that helps someone.

`pod 'PDFGenerator', git: 'https://github.com/sgr-ksmt/PDFGenerator', branch: 'swift-2.3'
`

**Comment by sgr-ksmt** [comment]
@louiscremen 
Sorry, I forgot to write phase `git: 'https://github.com/sgr-ksmt/PDFGenerator'` .
If you use specified branch of this library,  need to add `git:` and `branch:` phases.
I'll update README.
