### ISSUE TITLE
WKWebview Support

### ISSUE THREAD

**Issue by afshawnlotfi** [sgr-ksmt/PDFGenerator#74]
Hi I'm using this with a Webkit Webview and the problem is it generates the giant pdf but it only shows the part of the webpage you are currently on and the rest remains blank. I tried this with a UIWebview and it loads everything except the images because UIWebview has some condition where it doesn't load images unless the UIScrollView event has ended. I tried even automating the scroll to load the images and then generate the pdf but still that hasn't worked. Please fill me in on ways to get around both these issues. I have spent hours trying to figure this out and still have come short on an answer. Thank you so much.

**Comment by afshawnlotfi** [comment]
I figured it out by placing timers and letting the wkwebview render

**Comment by fanstudiouk** [comment]
Any ideas on how to fix this? Still happening after updating to iOS11...

**Comment by robert-cronin** [comment]
I'm having issues with this still in 2018, my problem is exactly as described above. Looks like this issue was raised and then closed with no resolution provided.

**Comment by afshawnlotfi** [comment]
Lol I just wrote my own implementation by now. Literally wrote some hacky thing to manually scroll through the webview and take a screenshot

**Comment by robert-cronin** [comment]
Whatever works I guess! I figured out how to do it using webView.viewPrintFormatter() and a custom function to render the html with images converted into base64 strings. It's not exactly related to the use of this pod but I can share the code if anyone wants it.

**Comment by gmarzloff** [comment]
@robert-cronin can you share your method for getting a full `WKWebview` saved to pdf? Thanks!
