### ISSUE TITLE
Scroll View

### ISSUE THREAD

**Issue by Shanlon** [sgr-ksmt/PDFGenerator#8]
When creating the PDF, I have an embedded UICollectionView in the center of the UIView. When generating the PDF, if does not account of the extra spacing with the UICollectionView.
- Does the entire UIView need to be embedded within a scroll view, and if so does it account for embedded scroll views?

**Comment by sgr-ksmt** [comment]
@Shanlon 
Sorry for replying late.

Please give me some code or figure of view's hierarchy or screenshot. :cry:

**Comment by Shanlon** [comment]
@sgr-ksmt Thanks for the response :+1: 
The PDF setup looks like: UIView - Information, CollectionView, Information.
