### ISSUE TITLE
Private Keys in .travis.yml?

### ISSUE THREAD

**Issue by wesbillman** [sgr-ksmt/PDFGenerator#80]
https://github.com/sgr-ksmt/PDFGenerator/blob/master/.travis.yml#L33
and
https://github.com/sgr-ksmt/PDFGenerator/blob/master/.travis.yml#L42

**Comment by wesbillman** [comment]
@sgr-ksmt you probably want to remove these, and use `ENV` on travis instead.

**Comment by sgr-ksmt** [comment]
@wesbillman 

Thank you for the report!
 I have already deleted it from master branch because I have not used it already 😢 .
